### ISSUE TITLE
Translate the App

### ISSUE THREAD

**Issue by 648480505** [Zoxcore/trifa_material#217]
Translation platforms can only translate strings and cannot translate other types

**Comment by zoff99** [comment]
can you give more details? what should be translated?

**Comment by 648480505** [comment]
> 你能提供更多细节吗？应该翻译什么？

Button, function description in settings, etc

**Comment by 648480505** [comment]
> they can be translated. you can help by making a PR.

src/main/kotlin/org/briarproject/briar/desktop/ui/AddGroup.kt

 Spacer(modifier = Modifier.height(30.dp))
        Row {
            Spacer(modifier = Modifier.width(35.dp))
            Text(fontWeight = FontWeight.ExtraBold,
                fontSize = 16.sp,
                text ="Important Notice: ")
            Text(fontWeight = FontWeight.Normal,
                fontSize = 16.sp,
                text ="Joining a Tox Public group for the first time can take a long time, even up to 30 minutes")
                
  Translate the content in the text, but I don't know programming. I hope to be able to translate it on platforms such as Weblate.

**Comment by zoff99** [comment]
its simple replace text like
`
"Important Notice: "
`
with

`
i18n("ui.group.important_notice")
`

then add an entry in `trifa_material.properties` file like this:
`
ui.group.important_notice=Important Notice: 
`

after that this string will be translateable with weblate.
and repeat for all Texts ...

**Comment by 648480505** [comment]
> its simple replace text like `"Important Notice: "` with
> 
> `i18n("ui.group.important_notice")`
> 
> then add an entry in `trifa_material.properties` file like this: `ui.group.important_notice=Important Notice: `
> 
> after that this string will be translateable with weblate. and repeat for all Texts ...

Thank you for teaching me, I have learned.
