### ISSUE TITLE
From scratch, no point

### ISSUE THREAD

**Issue by fcore117** [Zoxcore/trifa_material#288]
Why abandon fast qTox and create huge chunky fat application from scratch? qTox was basically near end and needed finalizing touches. Is there somewhere who continues qTox?

**Comment by zoff99** [comment]
qtox should not be used anymore.
see: https://github.com/Zoxcore/qTox_enhanced/issues/6
almost every component of qtox is end-of-life.
mainly qt5.x https://www.qt.io/blog/qt-5.15-extended-support-for-subscription-license-holders

**Comment by fcore117** [comment]
I want to believe someone moves to qt6 and continues development of lightweight qTox which is already functioning.
