### ISSUE TITLE
Does installing the debian deb work?

### ISSUE THREAD

**Issue by emdee-is** [Zoxcore/trifa_material#69]
Does installing the debian deb work?
```
dpkg -i github.com/Zoxcore/trifa_material/releases/download/nightly/trifa-material_nightly.deb
(Reading database ... 359569 files and directories currently installed.)
Preparing to unpack .../trifa-material_nightly.deb ...
Unpacking trifa-material (1.0.3-1) over (1.0.3-1) ...
Setting up trifa-material (1.0.3-1) ...
# which trifa
# which trifa-material
```
Is there something installed - doesn't look like it. Looks like a silent failure.

Can you distribute a standalone jar, and some documentation on what JAVA it requires or has been tested with?

**Comment by emdee-is** [comment]
Thanks - /opt/trifa-material/bin/trifa_material
Maybe a note during the install to say it's installed in /opt would help, as
trifa_material is not on the PATH.

Can you distribute a stand-alone jar for say gentoo?

How's the NOISE handshake working out? You've answered the question I raised about if it's possible to introduce it on the network backwards-compatably - great news. How does this work - each hand shake tries NOISE and fails to regular. I looked in the documentation but couldn't find anything :-)

Are menubars too horribly depasse? 

I think you need to offer bigger font sizes - they're too small for me,,,
The UI scale does nothing AFAIKT.

I hate with a passion grey not black fonts - eyestrain.

a mouse-toast popup over the icons would help.

the whole top right doesn't mean much to me - the design is too minimalistic for me to understand it. Words above the icons would help a lot.

I see no red/green/yellow indicator like qtox's dots to tell me if I/they are connected.

I sent my qtox an invite but nothing was received.

My qtox sent me an invite but nothing was received.

Why do I have a "new friend #0" who I didn't invite?

Would any import mechanism to import your friends/groups from an existing .tox be possible? You could  use https://git.plastiras.org/emdee/tox_profile to dump the .tox and parse the output. It would help acceptance.

Your application icon is too similar to qtox to mean anything different.

about:category:dependencies is empty.

Where do I set my nick?

Where do I set my status_message?

Have you listed it on tox.chat/clients yet?

**Comment by zoff99** [comment]
the original issue is fixed. deb install works.
